project:
  type: website

website:
  title: "Learning with sckinta"
  site-url: https://learniningwithsckinta.netlify.app/
  description: "This is Chun Su's personal blog"
  navbar:
    right:
      - text: Posts
        href: posts.qmd
      - text: Talks
        href: talks.qmd
      - text: CV
        href: https://sckinta.github.io/datadrivencv_cs/cv_render
format:
  html:
    theme: 
        light: cerulean
        dark: darkly
    css: styles.css
    code-fold: show
    code-overflow: scroll


editor: source

execute:
  freeze: true

listing:
  id: posts
  contents: posts
  type: grid
  image-placeholder: "/posts/bitbites_thumb.png"